### PR TITLE
Add OffMeshLink, Add Runtime support

### PR DESCRIPTION
**Pull request by orangeagain**
compatible offMeshLink
add runtime support

### CODE REVIEW

**Comment by holomatt** [comment]
the runtime methods work great with my NavMeshComponents use case. thanks for creating it!

**Comment by orangeagain** [comment]
> the runtime methods work great with my NavMeshComponents use case. thanks for creating it!

Thank for you like it! a clear version is commit.

**Comment by holomatt** [comment]
Request: eDimitry's version has a "Cheat Offset Value" to prevent the links from cutting through the edge of ledges since NavMesh often starts farther in than the edge of the geo. Relevant snippet from eDimitry's version is in CheckPlacePosHorizontal method. (https://pastebin.com/2CPPtTy1)

**Comment by idbrii** [comment]
I appreciate the enthusiasm, but as I said in #4 and #5, I think navgen at runtime is better handled by the code changing your geo and I don't want to maintain support for legacy components.

Additionally, this PR has a bunch of extra stuff in it: a KinematicCharacterController package, the unity-navgen example branch, and 620 changed files! I don't want to ask you to clean it up and then decline your PR, so I'll close this PR.

holomatt: I was intentionally trying to avoid copying eDimitry's code so I could post a solution with a clear license. However, I think it's be a great idea to take eDimitry's solution and make a new project that pulls in any improvements I have here or that orangeagain made.

**Pull request closed without merging**
